apiVersion: batch/v1
kind: CronJob
metadata:
  name: sample-cronjob
spec:
  schedule: "0 8 * * 1"  # Run every week
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: sentiment-analysis-job
            image: sg6428/tweet-sentiment-analysis:latest
            command: ["python", "train.py"]
            env:
            - name: CKPT_DIR
              value: /mnt/data/ckpt
            - name: MODEL_DIR
              value: /mnt/data/model_dir
            - name: MAX_TOKEN_LENGTH
              value: "128"
            - name: RETRAIN_DATA_PATH
              value: /mnt/data/data_output
            volumeMounts:
            - name: model-volume
              mountPath: /mnt
          volumes:
          - name: model-volume
            hostPath: 
              path: /host_mount
          restartPolicy: OnFailure