apiVersion: v1
kind: Service
metadata:
  name: fastapi-app-service
spec:
  selector:
    app: sentiment-analysis-app
  ports:
  - protocol: TCP
    port: 9696
    targetPort: 8000
  type: LoadBalancer